### PR TITLE
Springboard updates

### PR DESCRIPTION
**Pull request by garrett**
I've ported all the changes from Springboard back into Project Atomic, and have fixed a number of things to ensure it works.

Also, I have updated all the gems (except those that are specifically locked — which now includes the version of Bootstrap used, as it does change the style a little in new versions).

### CODE REVIEW

**Comment by garrett** [comment]
After merging and making these changes, everything looks perfect to me. I've asked @jasonbrooks and @tigert to review it.

@jasonbrooks says it looks good to him. (I haven't heard back from @tigert so far; he didn't get a chance to review it today.)

**Comment by cgwalters** [comment]
What is Springboard?

**Comment by garrett** [comment]
Springboard is the Middleman config we use for building sites, including ProjectAtomic.io.

https://github.com/OSAS/middleman-springboard

Several other sites use it too, including <http://community.redhat.com/> and <http://manageiq.org/> (hence all the changes).

Also worthy of mentioning: These changes include an interactive admin UI for editing blog posts. (It's only available when you run it locally, in development mode. It doesn't get compiled for production.)

**Comment by garrett** [comment]
FWIW: When you run the server locally, the admin UI is available at <http://0.0.0.0:4567/admin/>

**Comment by garrett** [comment]
Added a few fixes; it should build completely again. (We'll see what Travis CI says.)

**Pull request merged**
