### PR TITLE
add Atomic Registry summary to home page

### PR DESCRIPTION
**Pull request by aweiteka**
@jberkus here's what I came up with, combining Atomic App and Nulecule. Let me know if this works.

### CODE REVIEW

**Comment by jberkus** [comment]
Are you ready for this to go live and be a thing?

**Comment by aweiteka** [comment]
> Are you ready for this to go live and be a thing?

Yes. Complete docs set landed today.

**Comment by jberkus** [comment]
Hmmm, generally like the idea but I need to do some work on it.  Creating new branch now ...

**Comment by jberkus** [comment]
I seems to me that if we're going to drop Atomic Registry on the home page, we need to have an annoucement about it, no?

**Comment by jberkus** [comment]
Replaced by PR #289

**Pull request closed without merging**
