### PR TITLE
Bexelbie docker brno 0914

### PR DESCRIPTION
**Pull request by jberkus**
Edited version, with photos injected.

### CODE REVIEW

**Comment by jberkus** [comment]
@bexelbie this will wait for your comments, presumably after the conference.

**Comment by bexelbie** [comment]
This appears to be functionally identical to #362 with the exception of the pictures being better inlined an the opening slide image removed.

It is fine.

**Comment by jberkus** [comment]
@bproffitt please check, I needed to do a bunch of editing and I'm not sure I got everything.  Thanks!

**Comment by bproffitt** [comment]
Looked at the article, made some minor changes. Ready to go.

**Pull request merged**
