### PR TITLE
update dockerfile

### PR DESCRIPTION
**Pull request by TomasTomecek**
* put app to /source and not to /tmp
 * cache `bundle install`

### CODE REVIEW

**Comment by cgwalters** [comment]
See #261

**Comment by TomasTomecek** [comment]
thanks for the pointer Colin; will wait till the other pr is merged and then I either rebase or close this

**Comment by jberkus** [comment]
Other PR is merged.  What's the advantage of using `bundle cache install`?

**Comment by TomasTomecek** [comment]
`bundle install` takes super-long; so we should do it first and copy sources inside afterwards so it's not so "easy" to invalidate cache.

**Comment by jberkus** [comment]
Tomas:

The bundle cache option seems to add about 20MB to the image size, and I didn't notice it being significantly faster to build.

**Comment by TomasTomecek** [comment]
okay, let's drop this then

**Pull request closed without merging**
