### PR TITLE
Small changes to get kubernetes 1.0 running

### PR DESCRIPTION
**Pull request by fmpwizard**
I had to make those two changes to get kubernetes working on a Fedora Atomic host with all updates applied.

### CODE REVIEW

**Comment by mscherer** [comment]
That look good, but why should the ServiceAccount be removed ?

**Comment by fmpwizard** [comment]
Thanks for looking at it, I had to remove ServiceAccount because I got the error from
https://github.com/GoogleCloudPlatform/kubernetes/issues/11222

`no API token found for service account default/default, retry after the token is automatically created and added to the service account`

maybe there is a better way to handle this error, I'm not sure what that would be though

**Comment by nzwulfin** [comment]
I haven't reviewed the guide for the k8s 1.0 launch yet, there've been some big changes to the way services work.

I think this is a good workaround until we can get to a full review for 1.0.

**Comment by fmpwizard** [comment]
thanks for merging it

**Pull request merged**
