### PR TITLE
add deps of create-post.rb to Gemfile

### LINKED ISSUE #173: create_post.rb doesn't work
```
$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- launchy (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:4:in `<main>'

$ gem install launchy
Fetching: launchy-2.4.3.gem (100%)
Successfully installed launchy-2.4.3
Parsing documentation for launchy-2.4.3
Installing ri documentation for launchy-2.4.3
Done installing documentation for launchy after 1 seconds
1 gem installed

$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chronic (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:6:in `<main>'

$ gem install chronic
Fetching: chronic-0.10.2.gem (100%)
Successfully installed chronic-0.10.2
Parsing documentation for chronic-0.10.2
Installing ri documentation for chronic-0.10.2
Done installing documentation for chronic after 1 seconds
1 gem installed

$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- slop (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:7:in `<main>'

$ gem install slop
Fetching: slop-4.2.0.gem (100%)
Successfully installed slop-4.2.0
Parsing documentation for slop-4.2.0
Installing ri documentation for slop-4.2.0
Done installing documentation for slop after 0 seconds
1 gem installed

$ ./create-post.rb
./create-post.rb:15:in `<main>': undefined method `parse!' for Slop:Module (NoMethodError)
```

### PR DESCRIPTION
**Pull request by TomasTomecek**
Should fix #173

### CODE REVIEW

**Comment by jberkus** [comment]
Maybe I'm building this wrong, but "launchy" still doesn't seem to work.

[root@ed9459c0c70c ruby]# ./create-post.rb 
./create-post.rb:4:in `require': cannot load such file -- launchy (LoadError)
	from ./create-post.rb:4:in `<main>'

**Comment by TomasTomecek** [comment]
@jberkus having the same issue; I've done this PR because of https://github.com/projectatomic/atomic-site/issues/173#issuecomment-173705163

**Comment by jberkus** [comment]
I'm just saying that the PR doesn't seem to fix the issue, at least not when I test it.

**Comment by jberkus** [comment]
Superceded by #281.  Closing.

**Pull request closed without merging**
