### PR TITLE
Shishir a412ed daemon option basedevicesize

### PR DESCRIPTION
**Pull request by jberkus**
Replaces @shishir-a412ed PR for this blog post.

@shishir-a412ed please approve.  @bproffitt you can publish this as soon as Shishir approves the new version.

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
1) Can we change the title to {Increasing the Base Device Size on Docker `Daemon` Restart}? Docker has a lot of components in it's ecosystem, we need to specific of what we are restarting (daemon in this case).
2) Can we change the author to `Shishir Mahajan` (Init Cap) instead of `shishir` ?
3) Can we add `docker-storage` in the tags ?

Apart from these 3, the blog LGTM.

Shishir

**Comment by jberkus** [comment]
Shishir:

The "author" is actually a keyword which looks up your name in the authors.md file.  Other changes made.

**Comment by shishir-a412ed** [comment]
@jberkus @bproffitt Point 1 is still uncovered.

**Comment by jberkus** [comment]
It's getting fixed in Brian's copy.

**Comment by bproffitt** [comment]
Which has been live for a while now. Posted and social media posted.

BKP

On Wed, Mar 30, 2016 at 12:04 PM, Josh Berkus <notifications@github.com>
wrote:

> It's getting fixed in Brian's copy.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/pull/285#issuecomment-203504650>
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by shishir-a412ed** [comment]
@jberkus @bproffitt It's all good :)
Thank you guys for all the help !

**Pull request merged**
