### PR TITLE
Edited 2016-03-04-atomic-site-on-atomic-app.md based on @jlebron changes

### PR DESCRIPTION
**Pull request by bproffitt**

### CODE REVIEW

**Comment by jlebon** [comment]
@bproffitt Ahh sorry I didn't see that PR before opening #259 (it references the wrong blog post in the PR title). That said, you removed a chunk a bit too large at the end there. It should just remove lines 80 and 81, and keep the rest under that.

Feel free to update this PR and close #259, or just use #259.

**Comment by bproffitt** [comment]
My fault. I assumed a much larger "section" than what you intended.

BKP

On Thu, Mar 10, 2016 at 10:59 AM, Jonathan Lebon <notifications@github.com>
wrote:

> @bproffitt <https://github.com/bproffitt> Ahh sorry I didn't see that PR
> before opening #259
> <https://github.com/projectatomic/atomic-site/pull/259> (it references
> the wrong blog post in the PR title). That said, you removed a chunk a bit
> too large at the end there. It should just remove lines 80 and 81, and keep
> the rest under that.
>
> Feel free to update this PR and close #259
> <https://github.com/projectatomic/atomic-site/pull/259>, or just use #259
> <https://github.com/projectatomic/atomic-site/pull/259>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/pull/258#issuecomment-194922574>
> .
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by jberkus** [comment]
I'm confused, where are we with this?

**Comment by bproffitt** [comment]
We should be using #259

On Fri, Mar 11, 2016 at 6:37 AM, Josh Berkus <notifications@github.com>
wrote:

> I'm confused, where are we with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/pull/258#issuecomment-195332493>
> .
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by jberkus** [comment]
Closing this as redundant.

**Pull request closed without merging**
