### PR TITLE
Registry landing page

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by jberkus** [comment]
Why are you opening a PR if you aren't ready for merge?

**Comment by veillard** [comment]
On Mon, Feb 22, 2016 at 05:17:39PM -0800, Josh Berkus wrote:
> Why are you opening a PR if you aren't ready for merge?
> 

  Because a PR seems the standard way to get patches discussed in a github
environment ?

Daniel

-- 
Daniel Veillard      | Open Source and Standards, Red Hat
veillard@redhat.com  | libxml Gnome XML XSLT toolkit  http://xmlsoft.org/
http://veillard.com/ | virtualization library  http://libvirt.org/

**Comment by aweiteka** [comment]
> Because a PR seems the standard way to get patches discussed in a github environment ?

Yes, that was the thought. I wanted to give folks a chance to see the approach while we wait for dependent work in origin and cockpit to complete.

So far there's a strong demand for real docs, which is not a lot of effort. That would make this doc focused on introducing the topic then pointing to documentation for quickstart and more advanced topics.

**Comment by jberkus** [comment]
Ah, ok.  I really didn't know what you wanted here; there were no comments to indicate that you were looking for review.  Reviewing now ...

**Comment by jzb** [comment]
I'm fine with opening a PR but it's probably a good idea to announce this on one of the lists, like atomic-devel - otherwise only folks who are watching the repository are going to see it.

**Comment by jberkus** [comment]
Looks pretty good.  Some suggestions:

"It is recommended that external storage be provided at this mountpoint or configure the registry for cloud storage."
better:
"As image storage can become quite large, we recommend either mounting this directory on external, redundant storage, or configuring the registry for cloud storage."  
... would also be good to have a link to docs on configuring for cloud storage.

"The CLI client is not installed on the host system but it is available by entering the origin-master container on the Atomic Registry host system. The client may be installed on a remote system. See documentation for installing and using the remote CLI client."
- it might do to have more of an explanation of the origin-master container here.
- there's no way to enter the origin-master container via the cockpit interface?
- would be better to move the remote option to the bottom of this section

**Comment by aweiteka** [comment]
@garrett is there a better graphic or icon we can use for this?

**Comment by aweiteka** [comment]
@jberkus the docs this points to have landed. Ready to merge if there are no further comments.

Note: this is not linked yet from the main site so it's a "soft launch". We need to figure out the best way to link from the main site. I can submit a PR with whatever works.

**Comment by jberkus** [comment]
Merging.  However, this does not *link* the registry page from anywhere.  We'll need to do a separate PR to redesign some other page to link it in.

**Pull request merged**
