### PR TITLE
Fix build on Openshift

### PR DESCRIPTION
**Pull request by mscherer**
So I have been trying to get the website build on openshift v3 since a long time. I did managed 1 year ago, but since Openshift Online did took a while to appear, I did put that work on the backburner. 

Now that Openshift Online v2 is going away and v3 is around the corner, I started to look again. And I did wrote a s2i builder for middleman, that can be used like this:
```
oc new-build quay.io/osas/s2i-middleman~https://github.com/mscherer/atomic-site#fix_build_openshift
```

I tested on a local cluster, it build. I didn't verify the layout (as I had to touch to update bootstrap -sass version, it might have changed. I didn't verify the container, and there is surely something wrong with it (cause nginx give me 404).  

There is for now 2 commits:
- one to update the set of gems to build on Fedora 26
- one to update sass after previous gem update

### CODE REVIEW

**Comment by mscherer** [comment]
So the problem of the CI is due to travis using a too old ruby version. I can take a look at that, but then I would need to decide what version to use, which impact the builder and the users.

As for the 404, it got fixed with https://github.com/OSAS/s2i-middleman/commit/eb6dc6cf404895f094c2d025aebfb80b209895dd 

I hope that no link rely on the behavior of that configuration.

**Comment by jberkus** [comment]
SO, if we have no CI for this, I'm not clear on how I can merge it; it would mean that all tests fail forever after.

**Comment by mscherer** [comment]
So we now have CI, and reusing the image used for openshift.

**Comment by jberkus** [comment]
Hey, so when I try this PR, there's severe CSS and display problems with the site.  None of the images load.  Why would the changes you applied cause that?

Screenshot: https://pasteboard.co/GXWzK7V.png

**Comment by jberkus** [comment]
It looks like there's some backwards-incompatible changes to TemplateEngine:

Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :lang is invalid
Haml::TempleEngine: Option :ugly is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :ugly is invalid
Haml::TempleEngine: Option :outvar is invalid

**Comment by jasonbrooks** [comment]
@mscherer Do we need all these gemfile changes? With an unchanged Gemfile.lock, it works fine.

**Comment by mscherer** [comment]
@jberkus strange, it didn't cause trouble during the test.

@jbrooks have you tried to build from zero on F26 ? The gemfile.lock change are kinda a side effect of the Gem change to update sass to a version that build fine

Also, what was the trick to add more memory to the builder (cause I did deploy and it failed)

**Comment by jasonbrooks** [comment]
@mscherer I was testing w/ the docker.sh, which used f25. To make it build with f26, I needed these changes, which didn't disrupt the formatting on the site:

```
bash-4.4$ git diff master:Gemfile.lock Gemfile.lock 
diff --git a/Gemfile.lock b/Gemfile.lock
index 510f3a1..cfd582f 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -4,7 +4,7 @@ GEM
   specs:
     activesupport (4.1.10)
       i18n (~> 0.6, >= 0.6.9)
-      json (~> 1.7, >= 1.7.7)
+      json (~> 2.1.0, >= 1.7.7)
       minitest (~> 5.1)
       thread_safe (~> 0.1)
       tzinfo (~> 1.1)
@@ -62,7 +62,7 @@ GEM
     htmlentities (4.3.3)
     http_parser.rb (0.6.0)
     i18n (0.7.0)
-    json (1.8.2)
+    json (2.1.0)
     kramdown (1.6.0)
     launchy (2.4.3)
       addressable (~> 2.3)
@@ -131,7 +131,7 @@ GEM
     net-ssh (2.9.2)
     nokogiri (1.6.6.2)
       mini_portile (~> 0.6.0)
-    oj (2.12.1)
+    oj (3.3.9)
     open-uri-cached (0.0.5)
     padrino-helpers (0.12.5)
       i18n (~> 0.6, >= 0.6.7)
@@ -167,7 +167,7 @@ GEM
       sprockets (~> 2.0)
       tilt (~> 1.1)
     stringex (2.5.2)
-    therubyracer (0.12.2)
+    therubyracer (0.12.3)
       libv8 (~> 3.16.14.0)
       ref
     thor (0.19.1)
```

**Pull request merged**
