### PR TITLE
Containering openvmtools

### PR DESCRIPTION
**Pull request by dav1x**

### CODE REVIEW

**Comment by giuseppe** [comment]
@jberkus do you know why the CI is failing?

**Comment by jberkus** [comment]
Looks like Middleman is broken again.  Oh, @mscherer?

**Comment by jberkus** [comment]
Leaving the tests aside, @dav1x, why publish the article in its entirety if it's already up at developers.redhat.com?   I'd be more inclined to post a link.

**Comment by dav1x** [comment]
Link would be fine too. Just looking to get the content out there.

**Comment by mscherer** [comment]
I suspect the root cause is that dphillips is not in authors.yml (error is kinda cryptic, I am sure we can do better)

**Comment by jberkus** [comment]
I'll link to the developers.redhat.com article in all the ProjectAtomic social media.

**Comment by jberkus** [comment]
This has been shared with ProjectAtomic social media.  Given that, I'm closing this.

**Pull request closed without merging**
