### PR TITLE
vagrant-service-manager 0.0.3 release announcement

### PR DESCRIPTION
**Pull request by bexelbie**
@navidshaikh will do the release on 29 Feb

This draft is believed to be technically complete.  It has been reviewed by @navidshaikh @LalatenduMohanty and @bexelbie

### CODE REVIEW

**Comment by navidshaikh** [comment]
ping @jberkus @jzb

**Comment by jberkus** [comment]
For some reason I'm not getting all notifications from Github, sorry, will investigate.

@bproffitt , this post is ready to go.

**Comment by bexelbie** [comment]
@bproffitt does this need any mods before I merge it?

**Comment by jberkus** [comment]
It doesn't, we just break it up so that at least 2 people look at every post.

**Pull request merged**
