### PR TITLE
add feed icon and link

### LINKED ISSUE #213: Blog feed is not added to HTML
Although a [feed](http://www.projectatomic.io/blog/feed.xml) is generated, it's not found in the website's HTML code, making it harder to add to RSS readers.

### PR DESCRIPTION
**Pull request by bexelbie**
Fixes #213

### CODE REVIEW

**Comment by jberkus** [comment]
I've tested all three feed and social media changes together.  @bproffitt, please sign off and we'll merge/deploy.

**Comment by bproffitt** [comment]
Checked on local server. Looks good.

BKP

On Mon, Feb 22, 2016 at 8:29 PM, Josh Berkus <notifications@github.com>
wrote:

> I've tested all three feed and social media changes together. @bproffitt
> <https://github.com/bproffitt>, please sign off and we'll merge/deploy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/pull/237#issuecomment-187465164>
> .
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by bproffitt** [comment]
However, it seems broken on the main site.

http://www.projectatomic.io/blog/feed.xml is not working.

BKP

On Tue, Feb 23, 2016 at 7:43 AM, Brian Proffitt <bproffit@redhat.com> wrote:

> Checked on local server. Looks good.
>
> BKP
>
> On Mon, Feb 22, 2016 at 8:29 PM, Josh Berkus <notifications@github.com>
> wrote:
>
>> I've tested all three feed and social media changes together. @bproffitt
>> <https://github.com/bproffitt>, please sign off and we'll merge/deploy.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/projectatomic/atomic-site/pull/237#issuecomment-187465164>
>> .
>>
>
>
>
> --
> Brian Proffitt
> Principal Community Analyst
> Open Source and Standards
> @TheTechScribe
> 574.383.9BKP
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by bproffitt** [comment]
Wait, no, never mind, it's fine. All changes good.

BKP

On Tue, Feb 23, 2016 at 7:52 AM, Brian Proffitt <bproffit@redhat.com> wrote:

> However, it seems broken on the main site.
>
> http://www.projectatomic.io/blog/feed.xml is not working.
>
> BKP
>
> On Tue, Feb 23, 2016 at 7:43 AM, Brian Proffitt <bproffit@redhat.com>
> wrote:
>
>> Checked on local server. Looks good.
>>
>> BKP
>>
>> On Mon, Feb 22, 2016 at 8:29 PM, Josh Berkus <notifications@github.com>
>> wrote:
>>
>>> I've tested all three feed and social media changes together. @bproffitt
>>> <https://github.com/bproffitt>, please sign off and we'll merge/deploy.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/projectatomic/atomic-site/pull/237#issuecomment-187465164>
>>> .
>>>
>>
>>
>>
>> --
>> Brian Proffitt
>> Principal Community Analyst
>> Open Source and Standards
>> @TheTechScribe
>> 574.383.9BKP
>>
>
>
>
> --
> Brian Proffitt
> Principal Community Analyst
> Open Source and Standards
> @TheTechScribe
> 574.383.9BKP
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Pull request merged**
