### PR TITLE
Possible wrong master KUBE_API port in docs

### PR DESCRIPTION
**Pull request by eduardohki**
Hello,

I was trying to use the Atomic Getting Started Guide to setup Kubernetes on top of CentOS (non-Atomic), and lost about 2 hours trying to figure out why it didn't work initially.

So I found this configuration in Kube Master API section causing the error, and fixed it in my env changing it to port 8080.

Maybe my assumption is wrong, since this tutorial is for Fedora 25, but probably many others could face this problem described here.

Thanks!

### CODE REVIEW

**Comment by jberkus** [comment]
I think this is a difference between platforms; lemme test on different platforms to see what port is actually being used on each.

**Comment by eduardohki** [comment]
Thanks

In my environment, Kubernetes was using both 8080 and 6443 (SSL).

**Comment by jberkus** [comment]
So there's definitely a different port depending on how you installed this.  I need to do more testing to get the whole list, then I'll update.

**Comment by jberkus** [comment]
OK, tested distros.  I'm changing it to 6443 instead, because that worked everywhere.  Thank you for pointing out this bug!

**Comment by eduardohki** [comment]
Thanks @jberkus, I'm glad to help.

**Pull request closed without merging**
