### PR TITLE
Testing Nulecule on Debian Blog and author data update

### PR DESCRIPTION
**Pull request by bexelbie**

### CODE REVIEW

**Comment by jzb** [comment]
We have a few posts in the queue - is this urgent or can I schedule it for later this week?

**Comment by bexelbie** [comment]
Later is fine - I'd like to know a rough date when you can so I can start trying to solicit someone in the Debian Planet to mention it.  No rush on my account though.

**Comment by veillard** [comment]
On Tue, Jul 14, 2015 at 08:33:23AM -0700, jzb wrote:
> We have a few posts in the queue - is this urgent or can I schedule it for later this week? 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/projectatomic/atomic-site/pull/154#issuecomment-121283277

  not urgent IMHO, can go later

Daniel

-- 
Daniel Veillard      | Open Source and Standards, Red Hat
veillard@redhat.com  | libxml Gnome XML XSLT toolkit  http://xmlsoft.org/
http://veillard.com/ | virtualization library  http://libvirt.org/

**Comment by jzb** [comment]
I was thinking Thursday.

**Pull request merged**
