### PR TITLE
Cdrage atomic app 0 4 3 post

### PR DESCRIPTION
**Pull request by jberkus**
Fixed some things in @cdrage's post:

* changed to the correct date (March 2)
* fixed broken link
* fixed post title
* fixed formatting for shell code
* changed to "probably the last release before 1.0" because we really don't want to jinx ourselves.

### CODE REVIEW

**Comment by jberkus** [comment]
@bproffitt this is ready to go out tommorrow (march 2).  We don't want to send it out today because we already have too many posts today.

**Comment by cdrage** [comment]
@jberkus 

Haha whoops, I should of had more coffee. Docs are getting to my head.

Thanks so much for fixing these errors!

**Comment by jberkus** [comment]
@cdrage it's what I'm here for.  And why we have a two-person approval process; nobody can see their own typos.

**Comment by bproffitt** [comment]
Checks have failed, can still merge?

**Comment by jberkus** [comment]
No, looks like we have some ruby-related breakage.  Let me figure out what's causing it lest we take the site down.

**Comment by jberkus** [comment]
This might just  be Travis but I don't *know* that it is

**Comment by bproffitt** [comment]
I would check the metadata headers.

BKP

On Wed, Mar 2, 2016 at 11:48 AM, Josh Berkus <notifications@github.com>
wrote:

> No, looks like we have some ruby-related breakage. Let me figure out
> what's causing it lest we take the site down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/pull/250#issuecomment-191321519>
> .
>



-- 
Brian Proffitt
Principal Community Analyst
Open Source and Standards
@TheTechScribe
574.383.9BKP

**Comment by jberkus** [comment]
OK, date and header issue should be fixed now.

Here's a warning: you can't use the ":" character anywhere inside a field in the header, such as in the post title.

**Pull request merged**
