### PR TITLE
Developing with Mesos-Marathon on ADB

### PR DESCRIPTION
**Pull request by dharmit**
@jberkus @bproffitt I am pretty late in submitting this PR. Can you please suggest if it requires any changes?

### CODE REVIEW

**Comment by dharmit** [comment]
Looking at the travis job that failed, it doesn't seem like something I did could've caused it. But then I am no ruby expert. :joy:

**Comment by mscherer** [comment]
So the problem is on rails-assets.org which is out. Not much we can do , since we also do not have travis access. If you merge, it will go to a server I have access, and it might work (because we do not build from 0), but such is life of depending on free external services.

**Comment by mscherer** [comment]
the rails-assets.org website say: "This website is under heavy load (queue full), We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.". So maybe some kind of DOS going on, or similar.

If we were using our own CI, the solution would just be to use a local cache (squid, or a pulp based CDN), but we delegated so we have to wait until they fix.

**Comment by jberkus** [comment]
@dharmit  so, Marathon support isn't new (it showed up in 1.6).  And your blog post doesn't actually explain how to use it, just tells people it's there.  As such, I'm really not sure what the blog post is meant to show?

If you're going to do this, we'd really want a blog post which goes step-by-step through an example Marathon deployment using the ADB, with command-line and/or Cockpit examples.

**Comment by dharmit** [comment]
@jberkus Makes sense. Would adding [this](https://github.com/projectatomic/nulecule-library/tree/master/flask-redis-centos7-atomicapp) example make it more compelling? I'd written this example specifically for Mesos-Marathon provider.

**Comment by mscherer** [comment]
SO, as a FYI, rails-assets is back, so you can just push again (with -f) to retrigger travis check.

**Comment by dharmit** [comment]
@mscherer Sure, thanks misc.

**Comment by dharmit** [comment]
@jberkus can you check now? I've added the example and linked the repo where the code lives.

**Comment by jberkus** [comment]
@dharmit looks much better.  Questions:

1. did you actually do all those steps yourself?  Or are you just copy-and-pasting?  Because all of that stuff needs testing.
2. Doesn't atomicapp ship with the ADB?  Why would the user need to compile it from source?

**Comment by dharmit** [comment]
> did you actually do all those steps yourself? Or are you just copy-and-pasting? Because all of that stuff needs testing.

I did copy-pasting from my gist [0] which I intended to push to my blog but never did. Before pushing changes to this PR, I checked if things worked. :smiley: 

> Doesn't atomicapp ship with the ADB? Why would the user need to compile it from source?

I checked yesterday and it didn't seem to be there in the ADB box. `atomic` cli tool, however, is installed. But it doesn't support `--provider=marathon` at the moment.

[0] https://gist.github.com/dharmit/7a53c605914bb0fb87bc

**Comment by jberkus** [comment]
@dustymabe, is there a better way to do this with an RPM install?

**Comment by dustymabe** [comment]
@jberkus atomicapp is in epel-testing repo right now but it is a really old version: https://bodhi.fedoraproject.org/updates/?packages=atomicapp. @LalatenduMohanty - can we get this updated?

```
sudo yum install --enablerepo=epel-testing atomicapp
```

**Comment by jberkus** [comment]
I'll be going ahead with edits on this, targeting publication Wednesday.

**Comment by LalatenduMohanty** [comment]
@dustymabe https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-5d93f1948c

**Comment by dustymabe** [comment]
@LalatenduMohanty thanks!

**Comment by jberkus** [comment]
Sorry for delay, was out sick.  Planning on pushing this today.

**Comment by jberkus** [comment]
This is live, closing the PR

**Pull request merged**
