### PR TITLE
blog: upgrade from f27 -> f28

### PR DESCRIPTION
**Pull request by miabbott**
I basically took @dustymabe's post for f26 -> f27 and updated it for
Fedora 28.

### CODE REVIEW

**Comment by miabbott** [comment]
The only thing that sticks out in the article is the lack of a guide on running Kube containerized.  Back in the F26 -> F27 blog, @jasonbrooks was said to be working on one...

**Comment by dustymabe** [comment]
mostly LGTM. As stated would be nice to get something from @jasonbrooks

**Comment by jasonbrooks** [comment]
We can install the system containers as before -- actually, you should be able to continue using the f27 ones, through the magic of containers -- but for new installs, the method that I used to point people to, the kube ansible scripts, is now deprecated. I personally prefer kubeadm and package layering as a way to get kube running on atomic.

**Comment by sanjabonic** [comment]
Thanks for the PR!

**Pull request merged**
