### PR TITLE
Add blog post about Cockpit and Docker Restart Policy

### PR DESCRIPTION
**Pull request by stefwalter**
This is Cockpit 0.102

### CODE REVIEW

**Comment by jberkus** [comment]
Will review this Monday, travelling right now.

**Comment by jberkus** [comment]
Some breakage:

1. due to the inclusion of HTML stuff (the iframes) Middelman wants this file to be named  _.html.md instead of just .md in order to display correctly.

2. The image cockpit-logical-volume-one-dialog.png is missing from this pull.

**Comment by stefwalter** [comment]
Thanks @jberkus Made those changes.

**Comment by jberkus** [comment]
Moved to PR #307 in order to fix image link.

**Pull request closed without merging**
