### PR TITLE
blog for varlink and podman intro

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by sanjabonic** [comment]
Cool, thanks for this blog post.

**Comment by rhatdan** [comment]
@sanjabonic When are you going to post?

**Comment by dustymabe** [comment]
does varlink allow for you to host the API over HTTP/TCP (like a rest API)?

**Comment by baude** [comment]
@dustymabe yes, the implementation of that is not allowed in libpod yet.

**Comment by dustymabe** [comment]
> @dustymabe yes, the implementation of that is not allowed in libpod yet.

cool, yes I was just asking if varlink would allow it.. This is pretty powerful stuff

**Comment by rhatdan** [comment]
@dustymabe The truth is NO, But varlink can return a path to a socket either Unix Domain or TCP Socket where the server (Podman) can handle an incoming connection that could then be used to handle remote TTY Connections.

**Pull request merged**
