### PR TITLE
Add blog post for Cockpit and Kubernetes Volumes

### PR DESCRIPTION
**Pull request by stefwalter**
This is about the Cockpit 0.101 release.

### CODE REVIEW

**Comment by stefwalter** [comment]
CC @petervo Hope I got this right

**Comment by jberkus** [comment]
@petervo please sign of on this, will push Monday.

**Comment by petervo** [comment]
LGTM

**Comment by bproffitt** [comment]
Back from vacation; want me to push @jberkus ?

**Comment by jberkus** [comment]
Sure!

**Pull request merged**
