### PR TITLE
Jlebon pr/blog post atomic devmode

### PR DESCRIPTION
**Pull request by jberkus**
@jlebon blog post with some edits, including:

* copy-edits
* s/which/that
* change file date
* add notes about "enable boot menu" and "systemctl disable cloud-init"

### CODE REVIEW

**Comment by jberkus** [comment]
@bproffitt this is ready to publish tommorrow.

**Comment by jlebon** [comment]
@jberkus Seems like your commit just deletes the whole blog post.

**Comment by jberkus** [comment]
ooops.   That's the result of "mv" instead of "git mv".  Fixed.

**Comment by jlebon** [comment]
@jberkus Did the edits in #259.
This PR can be closed now.

**Pull request closed without merging**
