### PR TITLE
Docker Bnro Meetup 20160914 Blog

### PR DESCRIPTION
**Pull request by bexelbie**

### CODE REVIEW

**Comment by bexelbie** [comment]
@bproffitt @jberkus

**Comment by bexelbie** [comment]
Just realized I didn't include any pictures - I'll add them while you all review the text.

**Comment by jberkus** [comment]
So ... are pictures happening, or should we just run it without?

**Comment by jberkus** [comment]
Gah, there are pictures, and Github didn't notify me of changes.  Damned unstable APIs!

Reviewing, will push tommorrow.

**Comment by jberkus** [comment]
Hmmm ... so there's a bunch of images here, but none of them are linked into the post.  I just realized this after doing all of the grammar/punctuation edits, too.  Where are the images supposed to go?

**Comment by bexelbie** [comment]
@jberkus The images are in the last commit.  What commit are you working from?

**Comment by jberkus** [comment]
The image files are there.  It's just that they don't show in the article, anywhere.  There's no img tags.

**Comment by bexelbie** [comment]
Josh, please see lines 16, 18, 34, 119, and 164.  I just tested in middleman and they load.

I did not have a chance to test before I submitted the patch and did not notice that most of the images are missing the paths.  Also the filename has a . instead of a -.  I would submit a new update, but it sounds like you've already done some editing.

**Comment by jberkus** [comment]
Yeah, sorry, I'm having to merge the text by hand.  Taking a while.

**Comment by bexelbie** [comment]
Send me your edits, I'll merge them if you'd like.

**Comment by jberkus** [comment]
@bexelbie please take a look at PR #365.

That's my corrected version of the post, with photos.  If it's good, I'll ask Brian to review it tommorrow.

**Comment by bexelbie** [comment]
@jberkus are you replacing this with #365, if so, let's close.

**Pull request closed without merging**
