### PR TITLE
Added note about centos

### PR DESCRIPTION
**Pull request by lobocode**
Linking this important information

### CODE REVIEW

**Comment by jasonbrooks** [comment]
LGTM

**Comment by jasonbrooks** [comment]
@lobocode You should keep these PRs in separate branches

**Comment by lobocode** [comment]
@jasonbrooks What do you suggest?

**Comment by jberkus** [comment]
Hey, this merge is dirty ... you've picked up a blog post which isn't yours (and is already merged).  Is that something you can fix, or do I need to?

**Comment by lobocode** [comment]
@jberkus Sorry, but this commit, came personal notes I've done for a while in https://vitorlobo.gitbooks.io/atomicproject/content/ to better understand the operation of atomic registry and your needs.

I honestly don't remember the blog that you are referring to. Anyway, I leave open to show us what you mean. These, by the way, accusing me of plagiarizing quotes?

**Comment by jberkus** [comment]
@lobocode no, I'm saying that it looks like you did a rebase, resulting in a dirty merge for this one, because it includes a blog post from upstream which isn't part of your changes -- look at "files changed".  If you don't know how to fix that, I'll just take your text changes and add them myself.

**Comment by jasonbrooks** [comment]
I think we can close this one, replaced by #409

**Comment by lobocode** [comment]
@jberkus Ok. Sorry for the misunderstanding.

**Pull request closed without merging**
