### PR TITLE
intro: Emphasize kube more

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by jasonbrooks** [comment]
I think it's important still to emphasize rpm-ostree -- it's at least half of what's atomic about atomic.

**Comment by jberkus** [comment]
@cgwalters did you pull an old master?   getting a merge conflict

**Comment by cgwalters** [comment]
Rebased and updated.

**Comment by jberkus** [comment]
I like the idea, but not the wording.  I'll take a crack at this later today or tommorrow.

**Comment by cgwalters** [comment]
:telephone_receiver:

**Comment by cgwalters** [comment]
4 weeks later :calendar:  ?

**Comment by jberkus** [comment]
So, see this:  PR #336

That's what I'm thinking of in terms of further changes.  I think we really need to emphasise the stack (LDK) instead of just Kubernetes.

Also, this means changing our homepage too.

**Pull request merged**
